on:
  push:                 # プッシュした時に実行
    branches:           # ブランチを指定
      - master
name: Build and Deploy  # アクションの名称
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action     # JOBの名前
    runs-on: ubuntu-latest      # 仮想環境の種類を指定
    steps:
      - uses: actions/checkout@master   # リポジトリのデータを仮想環境にチェックアウトしてくるアクションを実行する

      - name: Use Node.js 12.13
        uses: actions/setup-node@v1     # Node.jsの環境をセットアップする
        with:
          node-version: '12.13'         # v12.13のバージョンのNode環境を使用する

      - name: List output files
        run: ls

      - name: Deploy
        env:                       # FTP環境の設定を行う
          CI: true
          FTP_HOST: ${{ secrets.FTP_HOST }}     # FTPサーバーのURLを設定
          FTP_USER: ${{ secrets.FTP_USER }} # FTPのユーザー名を設定
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} # FTPのパスワードを設定

        run: |
          npm install
          npm run deploy
